services:
  - type: web
    name: jamaliweb
    env: docker
    plan: starter
    dockerfilePath: ./Dockerfile
    dockerCommand: pipenv run gunicorn jamaliweb_project.wsgi:application -b 0.0.0.0:$PORT
    envVars:
      - key: ENVIRONMENT
        value: production
      - key: DEBUG
        value: 0
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: jamaliweb-db
          property: connectionString
    buildCommand: pipenv install --deploy --system
    startCommand: pipenv run gunicorn jamaliweb_project.wsgi:application -b 0.0.0.0:$PORT

databases:
  - name: jamaliweb-db
    databaseName: jamaliweb
    user: jamaliweb