services:
  - type: web
    name: jamaliweb
    env: python
    plan: starter
    buildCommand: ./build.sh
    startCommand: gunicorn jamaliweb_project.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: ENVIRONMENT
        value: production
      - key: DEBUG
        value: 0
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: jamaliweb-db
          property: connectionString

databases:
  - name: jamaliweb-db
    databaseName: jamaliweb
    user: jamaliweb