# Generated by Django 3.2 on 2025-06-22 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_blog_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='is_premium',
            field=models.BooleanField(default=False),
        ),
    ]
